// Dig, Hamster, Dig! - game content
'use strict';

const HAM_COLORS = {
  golden: { name: 'Golden', body: '#ecc189', belly: '#fffaf5' },
  cream: { name: 'Cream', body: '#f6e2bf', belly: '#fffaf0' },
  ginger: { name: 'Ginger', body: '#ec8a4c', belly: '#ffe6cf' },
  chocolate: { name: 'Cocoa', body: '#8e5d3f', belly: '#eccdaa' },
  gray: { name: 'Silver', body: '#adadba', belly: '#f1f1f6' },
  snow: { name: 'Snowy', body: '#e4ddd6', belly: '#ffffff' },
  midnight: { name: 'Midnight', body: '#4a4a5c', belly: '#cfcfe0' },
  pink: { name: 'Bubblegum', body: '#ffb1c8', belly: '#fff0f5' },
  sky: { name: 'Sky Blue', body: '#9fd6ff', belly: '#eef8ff' },
  lavender: { name: 'Lavender', body: '#c7b2ff', belly: '#f4efff' },
  mint: { name: 'Mint', body: '#9fe8c3', belly: '#eefff6' },
};

const ACCESSORIES = {
  leafhat: { name: 'Leaf Hat', slot: 'head', icon: '🍃' },
  flowercrown: { name: 'Flower Crown', slot: 'head', icon: '🌼' },
  bow: { name: 'Pink Bow', slot: 'head', icon: '🎀' },
  explorer: { name: 'Explorer Hat', slot: 'head', icon: '🤠' },
  beanie: { name: 'Cozy Beanie', slot: 'head', icon: '🧶' },
  earmuffs: { name: 'Earmuffs', slot: 'head', icon: '🎧' },
  spacehelmet: { name: 'Space Helmet', slot: 'head', icon: '🫧' },
  antennae: { name: 'Alien Antennae', slot: 'head', icon: '📡' },
  crown: { name: 'Golden Crown', slot: 'head', icon: '👑' },
  tophat: { name: 'Fancy Top Hat', slot: 'head', icon: '🎩' },
  sunglasses: { name: 'Cool Shades', slot: 'face', icon: '🕶️' },
  goggles: { name: 'Snow Goggles', slot: 'face', icon: '🥽' },
  monocle: { name: 'Monocle', slot: 'face', icon: '🧐' },
  mustache: { name: 'Mustache', slot: 'face', icon: '🥸' },
  scarf: { name: 'Stripy Scarf', slot: 'neck', icon: '🧣' },
  lei: { name: 'Flower Lei', slot: 'neck', icon: '🌺' },
  bowtie: { name: 'Bow Tie', slot: 'neck', icon: '🎗️' },
  medal: { name: 'Hero Medal', slot: 'neck', icon: '🏅' },
  cape: { name: 'Star Cape', slot: 'back', icon: '🦸' },
  backpack: { name: 'Backpack', slot: 'back', icon: '🎒' },
  wings: { name: 'Cosmic Wings', slot: 'back', icon: '🪽' },
  jetpack: { name: 'Jetpack', slot: 'back', icon: '🚀' },
};
const SLOTS = ['head', 'face', 'neck', 'back'];
const SLOT_NAMES = { head: 'Hats', face: 'Face', neck: 'Neck', back: 'Back' };

// Belt colour earned in each world's boss fight (yellow -> orange -> green -> black)
const BELTS = ['#f7d21e', '#ff8f1f', '#3fae4a', '#222222'];

const SKILLS = [
  { id: 'swipe', name: 'Paw Swipe', icon: '🐾', lvl: 1, pep: 0, meter: true, mult: 1, desc: 'Tap at the right time for extra damage!' },
  { id: 'cannon', name: 'Cheek Cannon', icon: '🌻', lvl: 2, pep: 3, mult: 1.4, desc: 'Spit seeds from your cheeks. Never misses!' },
  { id: 'snacktime', name: 'Snack Time', icon: '🍪', lvl: 3, pep: 4, heal: 0.4, desc: 'Munch a snack and heal 40% health.' },
  { id: 'roll', name: 'Hamster Roll', icon: '🌀', lvl: 4, pep: 5, meter: true, mult: 2, desc: 'Curl up and roll into a BIG hit!' },
  { id: 'dodge', name: 'Burrow Dodge', icon: '🕳️', lvl: 6, pep: 3, desc: 'Dig down, dodge the next attack, then pop up to counter!' },
  { id: 'sense', name: 'Whisker Sense', icon: '✨', lvl: 8, pep: 2, desc: 'Your whiskers find a weak spot: next hit is a critical!' },
  { id: 'tornado', name: 'Tornado Spin', icon: '🌪️', lvl: 10, pep: 7, hits: 3, mult: 0.9, desc: 'Spin super fast for three hits!' },
];

const KARATE_MOVES = [
  { id: 'chop', name: 'Karate Chop', icon: '🤚', pep: 0, meter: true, mult: 1.25, desc: 'Hi-YAH! Time it well.' },
  { id: 'kick', name: 'Flying Kick', icon: '🦶', pep: 5, meter: true, mult: 2.1, desc: 'A soaring kick!' },
  { id: 'block', name: 'Block Stance', icon: '🛡️', pep: 0, desc: 'Block 75% of the next hit and gain +3 Pep.' },
  { id: 'zen', name: 'Zen Breath', icon: '🧘', pep: 4, heal: 0.35, desc: 'Breathe... heal 35%.' },
  { id: 'fury', name: 'Dragon Fury', icon: '🐉', pep: 10, mult: 3.2, desc: 'The ultimate karate move!' },
];

const WORLDS = [
  {
    name: 'Garden Grounds', short: 'Garden', icon: '🌻',
    desc: 'Soft dirt, green grass and wiggly earthworms.',
    c: { sky1: '#7fd0ff', sky2: '#d4f1ff', top: '#69c24a', top2: '#4fa336', dirt: ['#b98250', '#a26f42', '#8c5e37'], tunnel: '#55382a', stone: '#a5a39d', speck: 'rgba(80,45,20,0.35)' },
    light: 8, dark: 0.62, stoneRate: 0.05,
    items: [
      { id: 'acorn', e: '🌰', name: 'Acorns' },
      { id: 'seed', e: '🌻', name: 'Sunflower Seeds' },
      { id: 'mushroom', e: '🍄', name: 'Mushrooms' },
      { id: 'carrot', e: '🥕', name: 'Carrots' },
    ],
    hostiles: [
      { id: 'worm', e: '🪱', name: 'Wiggly Earthworm', hp: 10, atk: 2, xp: 6, special: 'Wiggle Whip' },
      { id: 'ant', e: '🐜', name: 'Grumpy Ant', hp: 12, atk: 3, xp: 7, special: 'Bitey Chomp' },
      { id: 'beetle', e: '🪲', name: 'Bonky Beetle', hp: 16, atk: 3, xp: 9, special: 'Shell Bash' },
      { id: 'spider', e: '🕷️', name: 'Sneaky Spider', hp: 14, atk: 4, xp: 9, special: 'Web Wrap' },
    ],
    friends: [
      { id: 'ladybug', e: '🐞', name: 'Lulu Ladybug', role: 'helper', lines: ['Hi friend! Take this, it might help!', 'You dig so fast! Here, a little present!'] },
      { id: 'bee', e: '🐝', name: 'Buzzy Bee', role: 'helper', lines: ['Bzzz! I found this in a flower. For you!', 'Bzz-bzz! Keep digging, hero!'] },
      { id: 'snail', e: '🐌', name: 'Professor Shellby', role: 'riddler', lines: ['Ahem! Slow down, young hamster. Answer my riddle!'] },
    ],
    ambient: { hostile: 6, friend: 3, stones: 0, chests: 3, snacks: 6 },
    accessories: ['leafhat', 'flowercrown', 'bow', 'bowtie', 'backpack'],
    plan: [
      [{ type: 'collect', n: 3 }, { type: 'defeat', n: 1, who: 'worm' }, { type: 'clue' }],
      [{ type: 'collect', n: 3 }, { type: 'chest' }, { type: 'riddle', n: 1 }, { type: 'clue' }],
      [{ type: 'collect', n: 4 }, { type: 'defeat', n: 2 }, { type: 'riddle', n: 1 }, { type: 'clue' }],
    ],
    boss: {
      name: 'Queen Antoinette', e: '🐜', style: 'queen', hp: 70, atk: 5, xp: 90,
      attack: 'Royal Pinch', big: 'ROYAL STOMP', special: 'Worker Swarm', reward: 'medal',
      lines: ['"Who dares dig into MY palace? Those seeds are for my royal snack!"', '"Workers! Defend your queen!"', '"Impossible! A hamster... doing KARATE?!"', '"Fine, FINE! I\'ll give the seeds back... and say sorry."'],
    },
    mystery: {
      title: 'The Case of the Vanishing Seeds', giver: '🐞 Lulu Ladybug',
      intro: 'Oh no! Every night, sunflower seeds vanish from the garden... and something is carrying them UNDERGROUND! Find the clues 📜 and figure out who the thief is!',
      clues: [
        'Tiny footprints in the dirt... SIX little feet, marching in a neat line.',
        'A trail of seed shells leads to a tunnel with a tiny CROWN carved above the door.',
        'You overhear whispers: "Bring more seeds! Her Majesty is HUNGRY!"',
      ],
      question: 'Who is stealing the seeds?',
      options: ['Wiggly Earthworm', 'Professor Shellby the Snail', 'The Ant Queen', 'Buzzy Bee'],
      answer: 2,
      hint: 'Six legs... a crown... "Her Majesty"...',
    },
    riddles: [ // ordered easiest to hardest
      { q: "What has a neck but no head?", a: "A bottle", w: ["A giraffe", "A snake", "A worm"] },
      { q: "I have hands but I cannot clap. What am I?", a: "A clock", w: ["A glove", "A tree", "A crab"] },
      { q: "What has lots of teeth but can't bite?", a: "A comb", w: ["A shark", "A carrot", "A cloud"] },
      { q: "What has to be broken before you can use it?", a: "An egg", w: ["A seed", "A rock", "A stick"] },
      { q: "What can you catch but never throw?", a: "A cold", w: ["A ball", "A fish", "A frisbee"] },
      { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle", w: ["A hamster", "A tree", "A worm"] },
      { q: "What goes up but never comes down?", a: "Your age", w: ["A balloon", "A bird", "A ball"] },
      { q: "What gets wetter the more it dries?", a: "A towel", w: ["Rain", "A leaf", "A puddle"] },
      { q: "I'm full of holes but I can still hold water. What am I?", a: "A sponge", w: ["A bucket", "A net", "A cup"] },
      { q: "What can you hold in your right hand, but never in your left hand?", a: "Your left hand", w: ["A seed", "Your right hand", "A shadow"] },
    ],
  },
  {
    name: 'Jungle Depths', short: 'Jungle', icon: '🌴',
    desc: 'Tangled roots, hidden temples and sneaky snakes.',
    c: { sky1: '#5cc98a', sky2: '#c8f5c0', top: '#2f9e44', top2: '#227a33', dirt: ['#7a5a33', '#6a4c2a', '#5a3f22'], tunnel: '#2e2114', stone: '#6f8f6a', speck: 'rgba(30,80,30,0.35)' },
    light: 7, dark: 0.72, stoneRate: 0.08,
    items: [
      { id: 'banana', e: '🍌', name: 'Bananas' },
      { id: 'gem', e: '💎', name: 'Jungle Gems' },
      { id: 'feather', e: '🪶', name: 'Parrot Feathers' },
      { id: 'coconut', e: '🥥', name: 'Coconuts' },
    ],
    hostiles: [
      { id: 'snake', e: '🐍', name: 'Slithery Snake', hp: 28, atk: 6, xp: 15, special: 'Fang Strike' },
      { id: 'scorpion', e: '🦂', name: 'Spiky Scorpion', hp: 26, atk: 7, xp: 16, special: 'Tail Sting' },
      { id: 'lizard', e: '🦎', name: 'Lurking Lizard', hp: 24, atk: 6, xp: 14, special: 'Tail Smack' },
      { id: 'mosquito', e: '🦟', name: 'Mega Mosquito', hp: 18, atk: 6, xp: 12, special: 'Itchy Bite' },
      { id: 'croc', e: '🐊', name: 'Cranky Crocodile', hp: 38, atk: 7, xp: 20, special: 'Chomp Chomp' },
    ],
    friends: [
      { id: 'frog', e: '🐸', name: 'Froggy Hopsworth', role: 'helper', lines: ['Ribbit! I found this by the river. Take it!', 'Ribbit ribbit! Good luck down there!'] },
      { id: 'monkey', e: '🐒', name: 'Coco the Monkey', role: 'helper', lines: ['Ooh-ooh! A present for my digging buddy!'] },
      { id: 'parrot', e: '🦜', name: 'Captain Squawk', role: 'riddler', lines: ['SQUAWK! Answer me this, matey!'] },
      { id: 'sloth', e: '🦥', name: 'Slowpoke Sage', role: 'riddler', lines: ['Hellooo... think... slowly... about... this...'] },
    ],
    ambient: { hostile: 9, friend: 4, stones: 1, chests: 3, snacks: 5 },
    accessories: ['explorer', 'lei', 'sunglasses', 'mustache'],
    plan: [
      [{ type: 'collect', n: 4 }, { type: 'defeat', n: 2 }, { type: 'riddle', n: 1 }, { type: 'clue' }],
      [{ type: 'collect', n: 4 }, { type: 'defeat', n: 3 }, { type: 'riddle', n: 1 }, { type: 'clue' }],
      [{ type: 'collect', n: 5 }, { type: 'defeat', n: 3, who: 'snake' }, { type: 'riddle', n: 2 }, { type: 'clue' }],
    ],
    boss: {
      name: 'Sir Hissington the Python', e: '🐍', style: 'python', hp: 170, atk: 9, xp: 220,
      attack: 'Tail Whack', big: 'MEGA SQUEEZE', special: 'Hypno Eyes', reward: 'crown',
      lines: ['"Ssssso... you found my lair. The Golden Idol is MINE, little furball!"', '"Look into my eyesss... you are getting sssleepy..."', '"Karate?! Nobody told me hamsters knew KARATE!"', '"Ssss... fine. Take your shiny idol back. Hmph."'],
    },
    mystery: {
      title: 'The Lost Golden Idol', giver: '🦜 Captain Squawk',
      intro: 'SQUAWK! The Golden Idol of the Jungle Temple has been STOLEN! Without it the jungle flowers won\'t bloom. The thief hid somewhere deep underground. Gather the clues 📜!',
      clues: [
        'Smooth, shiny SCALES are scattered across the temple floor.',
        'There are NO footprints anywhere... the thief has no legs at all!',
        'A long wiggly track in the mud, and an echo from below: "Sssso ssshiny..."',
      ],
      question: 'Who stole the Golden Idol?',
      options: ['Froggy Hopsworth', 'Spiky Scorpion', 'Sir Hissington the Python', 'Coco the Monkey'],
      answer: 2,
      hint: 'Scales, no legs, and a hissing voice...',
    },
    riddles: [ // ordered easiest to hardest
      { q: "The more you take, the more you leave behind. What are they?", a: "Footsteps", w: ["Bananas", "Leaves", "Shadows"] },
      { q: "What has a head and a tail but no body?", a: "A coin", w: ["A snake", "A comet", "A tadpole"] },
      { q: "What runs but never walks, has a mouth but never talks, and has a bed but never sleeps?", a: "A river", w: ["A jaguar", "A clock", "A road"] },
      { q: "I speak without a mouth and hear without ears. I come alive in caves. What am I?", a: "An echo", w: ["A parrot", "A drum", "A ghost"] },
      { q: "Feed me and I grow, give me a drink and I die. What am I?", a: "Fire", w: ["A plant", "A monkey", "A sponge"] },
      { q: "What has many leaves but is not a plant?", a: "A book", w: ["A parrot", "A river", "A stone"] },
      { q: "I have keys but open no locks. I have space but no room. What am I?", a: "A keyboard", w: ["A treasure chest", "A temple", "A cage"] },
      { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M", w: ["A blink", "A heartbeat", "A shooting star"] },
      { q: "Forward I am heavy, but backward I am NOT. What am I?", a: "A ton", w: ["A boulder", "A gorilla", "A log"] },
      { q: "What word is spelled wrong in every dictionary?", a: "Wrong", w: ["Dictionary", "Mistake", "Jungle"] },
    ],
  },
  {
    name: 'Frosty Hollow', short: 'Snow', icon: '❄️',
    desc: 'Icy caves, sparkling crystals and howling wolves.',
    c: { sky1: '#a9c9ef', sky2: '#eef6ff', top: '#ffffff', top2: '#d6e6f7', dirt: ['#a9bdd6', '#8fa6c4', '#7890b2'], tunnel: '#2f3d5c', stone: '#d8f0ff', speck: 'rgba(255,255,255,0.45)' },
    light: 6, dark: 0.8, stoneRate: 0.1,
    items: [
      { id: 'crystal', e: '💠', name: 'Ice Crystals' },
      { id: 'mitten', e: '🧤', name: 'Lost Mittens' },
      { id: 'berry', e: '🫐', name: 'Frost Berries' },
      { id: 'bell', e: '🔔', name: 'Sleigh Bells' },
    ],
    hostiles: [
      { id: 'wolf', e: '🐺', name: 'Frostfang Wolf', plural: 'Frostfang Wolves', hp: 48, atk: 10, xp: 28, special: 'Frost Howl' },
      { id: 'crab', e: '🦀', name: 'Ice Crab', hp: 44, atk: 9, xp: 26, special: 'Pincer Freeze' },
      { id: 'sprite', e: '❄️', name: 'Frost Sprite', hp: 38, atk: 11, xp: 27, special: 'Icicle Shot' },
      { id: 'bat', e: '🦇', name: 'Cave Bat', hp: 40, atk: 9, xp: 25, special: 'Sonic Squeak' },
      { id: 'bear', e: '🐻‍❄️', name: 'Polar Bear', hp: 62, atk: 11, xp: 34, special: 'Big Bear Hug' },
    ],
    friends: [
      { id: 'penguin', e: '🐧', name: 'Pip the Penguin', role: 'helper', lines: ['Brrr! Hi! I slid all the way here to give you this!', 'Stay warm, friend!'] },
      { id: 'seal', e: '🦭', name: 'Sealie', role: 'helper', lines: ['Arf arf! Found this under the ice!'] },
      { id: 'owl', e: '🦉', name: 'Hoot the Wise', role: 'riddler', lines: ['Hoo-hoo... only a clever mind may pass. Listen closely...'] },
      { id: 'fox', e: '🦊', name: 'Riddlesnout the Fox', role: 'riddler', lines: ['Heh heh. Think you\'re clever? Try THIS one.'] },
    ],
    ambient: { hostile: 12, friend: 4, stones: 2, chests: 3, snacks: 5 },
    accessories: ['beanie', 'earmuffs', 'scarf', 'goggles'],
    plan: [
      [{ type: 'collect', n: 4 }, { type: 'defeat', n: 3 }, { type: 'riddle', n: 2 }, { type: 'clue' }],
      [{ type: 'collect', n: 5 }, { type: 'defeat', n: 4 }, { type: 'riddle', n: 2 }, { type: 'clue' }],
      [{ type: 'collect', n: 5 }, { type: 'defeat', n: 4, who: 'wolf' }, { type: 'riddle', n: 2 }, { type: 'depth', n: 15 }, { type: 'clue' }],
    ],
    boss: {
      name: 'Grumblefrost the Yeti', e: '', style: 'yeti', hp: 290, atk: 13, xp: 420,
      attack: 'Snowball Smash', big: 'AVALANCHE SLAM', special: 'Blizzard Breath', reward: 'tophat',
      lines: ['"GRAAAH! The Sun Crystal is MINE! It\'s the only warm thing down here!"', '"YOU CANNOT MELT GRUMBLEFROST!"', '"Wha--?! Tiny karate paws?! OUCH!"', '"*sniff* ...I was just cold. And lonely. Here... take the crystal back."'],
    },
    mystery: {
      title: 'The Frozen Heart of Winter', giver: '🐧 Pip the Penguin',
      intro: 'The Sun Crystal that keeps Frosty Hollow cozy has been taken! It\'s getting colder and colder... Find all the clues 📜 and think carefully. This mystery is trickier!',
      clues: [
        'HUGE footprints in the snow... much too big for a wolf, an owl or a penguin.',
        'Long WHITE FUR snagged on an icicle. (Penguins and owls have feathers, not fur!)',
        'The footprints show the thief walks on TWO big feet, not four paws. A grumbly voice echoes: "Mine! Warm and glowy!"',
      ],
      question: 'Who took the Sun Crystal?',
      options: ['Pip the Penguin', 'Frostfang the Wolf', 'Hoot the Wise Owl', 'Grumblefrost the Yeti'],
      answer: 3,
      hint: 'Huge feet, white fur, and walks on two legs...',
    },
    riddles: [ // ordered easiest to hardest
      { q: "What has one eye but cannot see?", a: "A needle", w: ["A pirate", "An owl", "A snowman"] },
      { q: "What has cities but no houses, forests but no trees, and water but no fish?", a: "A map", w: ["A snow globe", "A dream", "A painting"] },
      { q: "What can fill a whole room but takes up no space?", a: "Light", w: ["Snow", "A blanket", "Water"] },
      { q: "What can travel around the world while staying in one corner?", a: "A stamp", w: ["A snowflake", "A spider", "A compass"] },
      { q: "I'm light as a feather, yet the strongest yeti can't hold me for five minutes. What am I?", a: "Your breath", w: ["A snowflake", "An icicle", "A cloud"] },
      { q: "I shave every day, but my beard stays the same. Who am I?", a: "A barber", w: ["A yeti", "A goat", "A walrus"] },
      { q: "If you have me, you want to share me. If you share me, you don't have me anymore. What am I?", a: "A secret", w: ["A cookie", "A scarf", "A snowball"] },
      { q: "I am always in front of you, but you can never see me. What am I?", a: "The future", w: ["Your nose", "The wind", "A ghost"] },
      { q: "What disappears as soon as you say its name?", a: "Silence", w: ["A snowflake", "A shadow", "A bubble"] },
      { q: "A penguin is 3 years older than a seal. In 5 years the penguin will be 10. How old is the seal now?", a: "2", w: ["5", "7", "8"] },
      { q: "I am an odd number. Take away one letter and I become even. What number am I?", a: "Seven", w: ["Five", "Nine", "Eleven"] },
    ],
  },
  {
    name: 'Moon Base Mystery', short: 'Moon', icon: '🌙', bonus: true,
    desc: 'BONUS WORLD! Aliens: some friendly, some NOT.',
    c: { sky1: '#05061a', sky2: '#1d1b4a', top: '#d9d9e6', top2: '#a9a9c0', dirt: ['#8d8ca3', '#76758e', '#5f5e78'], tunnel: '#191830', stone: '#5a4f8c', speck: 'rgba(40,30,80,0.45)' },
    light: 5.5, dark: 0.86, stoneRate: 0.11,
    items: [
      { id: 'star', e: '⭐', name: 'Star Shards' },
      { id: 'cheese', e: '🧀', name: 'Moon Cheese' },
      { id: 'battery', e: '🔋', name: 'Glow Batteries' },
      { id: 'planet', e: '🪐', name: 'Mini Planets' },
    ],
    hostiles: [
      { id: 'invader', e: '👾', name: 'Space Invader', hp: 70, atk: 13, xp: 45, special: 'Pixel Blast' },
      { id: 'saucer', e: '🛸', name: 'Rogue Saucer', hp: 65, atk: 14, xp: 44, special: 'Tractor Zap' },
      { id: 'blob', e: '🦠', name: 'Cosmic Blob', hp: 78, atk: 12, xp: 46, special: 'Goo Splat' },
      { id: 'squid', e: '🦑', name: 'Kraken Minion', hp: 80, atk: 14, xp: 48, special: 'Ink Squirt' },
      { id: 'meteor', e: '☄️', name: 'Living Meteor', hp: 72, atk: 15, xp: 47, special: 'Fireball Dive' },
    ],
    friends: [
      { id: 'robot', e: '🤖', name: 'Beep-Bop', role: 'helper', lines: ['BEEP BOOP. GIFT PROTOCOL ACTIVATED.', 'BOOP. YOU ARE MY FAVORITE ORGANIC.'] },
      { id: 'mouse', e: '🐭', name: 'Moon Mouse', role: 'helper', lines: ['Squeak! A fellow rodent! Take this!'] },
      { id: 'oracle', e: '🔮', name: 'The Oracle Orb', role: 'riddler', lines: ['I see... a hamster... who must answer my riddle...'] },
      { id: 'stranger', e: '👽', name: 'Mysterious Alien', role: 'mystery', lines: ['...'] },
      { id: 'stranger', e: '👽', name: 'Mysterious Alien', role: 'mystery', lines: ['...'] },
      { id: 'stranger', e: '👽', name: 'Mysterious Alien', role: 'mystery', lines: ['...'] },
    ],
    ambient: { hostile: 14, friend: 6, stones: 3, chests: 3, snacks: 6 },
    accessories: ['spacehelmet', 'antennae', 'jetpack', 'cape', 'monocle'],
    plan: [
      [{ type: 'collect', n: 5 }, { type: 'defeat', n: 4 }, { type: 'riddle', n: 2 }, { type: 'friend', n: 1 }, { type: 'clue' }],
      [{ type: 'collect', n: 5 }, { type: 'defeat', n: 5 }, { type: 'riddle', n: 3 }, { type: 'clue' }],
      [{ type: 'collect', n: 6 }, { type: 'defeat', n: 5, who: 'squid' }, { type: 'riddle', n: 3 }, { type: 'clue' }],
    ],
    boss: {
      name: 'Zorblax the Space Kraken', e: '🐙', style: 'kraken', hp: 450, atk: 17, xp: 800,
      attack: 'Tentacle Slap', big: 'COSMIC CRUSH', special: 'Laser Ink', reward: 'wings',
      lines: ['"GLORB! You cracked my code, tiny earthling? The Glow Cores belong to ZORBLAX!"', '"Feel the power of EIGHT tentacles!"', '"How can something so FLUFFY hit so HARD?!"', '"Glorb... you win. The Moon shall glow again. Zorblax... is impressed."'],
    },
    mystery: {
      title: 'The Moon\'s Missing Glow', giver: '👽 Glorp',
      intro: 'Bleep-bloop! The Moon\'s Glow Cores were stolen and the Moon is going DARK! The thief left strange marks and a SECRET CODE. Collect the clues 📜 and crack the code! (Psst: some aliens down there are friendly... and some are NOT.)',
      clues: [
        'The Glow Core vault is covered in EIGHT round sucker marks.',
        'A scrap of paper with a secret code: 11 - 18 - 1 - 11 - 5 - 14   (Hint: A=1, B=2, C=3...)',
        'Beep-Bop the robot has metal claws, not suckers. And the Moon Mouse was eating cheese with you the whole time!',
      ],
      question: 'Crack the code! Who stole the Glow Cores?',
      options: ['Beep-Bop the Robot', 'Moon Mouse', 'Zorblax the Space Kraken', 'The Oracle Orb'],
      answer: 2,
      hint: 'Decode it: 11=K, 18=R, 1=A... and what has eight arms with suckers?',
    },
    riddles: [ // ordered easiest to hardest
      { q: "I have a face but no eyes. I change shape every night, but I make no light of my own. What am I?", a: "The Moon", w: ["A star", "A clock", "A mirror"] },
      { q: "What is always coming, but never arrives?", a: "Tomorrow", w: ["A comet", "A spaceship", "Midnight"] },
      { q: "The more of me there is, the less you can see. What am I?", a: "Darkness", w: ["Stars", "Cheese", "Light"] },
      { q: "What belongs to you, but other aliens use it more than you do?", a: "Your name", w: ["Your ray gun", "Your spaceship", "Your shadow"] },
      { q: "On the Moon, which weighs more: a kilogram of moon rocks or a kilogram of feathers?", a: "They weigh the same", w: ["Moon rocks", "Feathers", "Nothing weighs anything"] },
      { q: "A rocket takes 4 hours to reach a space station. If it flies twice as fast, how long does it take?", a: "2 hours", w: ["8 hours", "4 hours", "1 hour"] },
      { q: "A planet has 3 moons. Each moon has 3 craters. Each crater hides 3 aliens. How many aliens?", a: "27", w: ["9", "12", "81"] },
      { q: "What comes next? 1, 1, 2, 3, 5, 8, ...", a: "13", w: ["11", "10", "16"] },
      { q: "Decode this: 13 - 15 - 15 - 14   (A=1, B=2, ...)", a: "MOON", w: ["NOON", "MOOD", "LOOM"] },
      { q: "Unscramble \"LAPENT\" to find something in space.", a: "PLANET", w: ["COMET", "SATURN", "ROCKET"] },
      { q: "What 5-letter word becomes SHORTER when you add two letters to it?", a: "Short", w: ["Small", "Space", "Comet"] },
      { q: "Move every letter one step BACK in the alphabet (B becomes A): TUBS", a: "STAR", w: ["SUBS", "RTAR", "TURN"] },
      { q: "What letter comes next? O, T, T, F, F, S, S, E, ...", a: "N", w: ["T", "E", "O"] },
      { q: "I am the beginning of eternity, the end of time and space, and the start of every end. What am I?", a: "The letter E", w: ["A black hole", "The letter S", "Zero"] },
      { q: "Two mother aliens and two daughter aliens went to space, but only 3 aliens flew. How?", a: "Grandma, mom and daughter", w: ["One got lost", "One was invisible", "It's impossible"] },
    ],
  },
];

const HELP_STEPS = [
  { icon: '⬆️⬇️⬅️➡️', title: 'Dig!', text: 'Use the arrow keys (or WASD, or the on-screen buttons) to dig tunnels.' },
  { icon: '📋', title: 'Do your tasks', text: 'Your Task Bar shows what to find. Finish them all for a new wave of tasks.' },
  { icon: '🗿📜', title: 'Solve mysteries', text: 'Riddle Stones 🗿 and clever creatures ask riddles. Clue scrolls 📜 help you solve the world\'s mystery.' },
  { icon: '⚔️', title: 'Battle!', text: 'Bump into mean creatures to fight. Friendly ones 💬 may help you or give gifts!' },
  { icon: '🥋', title: 'Boss time', text: 'Beat 3 waves to find the Boss. You turn into KARATE HAMSTER!' },
  { icon: '⭐🎀', title: 'Grow & dress up', text: 'Level up to learn skills. Find accessories 🎁 and wear them in Dress Up!' },
];
